### ISSUE TITLE
Vivado Web Installer Obsolete

### ISSUE THREAD

**Issue by sslerose** [RedPitaya/redpitaya-knowledgebase#45]
The web installer client for Vivado 2020.1 is obsolete. Instructions in the https://github.com/RedPitaya/redpitaya-knowledgebase/blob/master//learn_fpga/3_vivado_env/tutorfpga1.rst (including the ReadTheDocs section) instruction set should be changed.

![image](https://github.com/RedPitaya/redpitaya-knowledgebase/assets/42822005/2f66f89e-7863-4452-b5de-759cec480580)

**Comment by Lightsaver7** [comment]
Thank you for opening this.

Updated instructions to use the full installer (35 GB tar.gz file). Web installers have been obsolete since AMD acquired Xilinx. The fix is live now.
